//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratories_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public int PatientId { get; set; }
        public int TestId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Medical_Tests Medical_Tests { get; set; }
    }
}
