//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratories_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_Tests()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
        public decimal TestPrice { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public override string ToString()
        {
            return $"{TestName} - {TestPrice}—Ì«·"; 
        }
    }
}
